import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        Image: "readonly",
        FileReader: "readonly",
        File: "readonly",
        Blob: "readonly",
        crypto: "readonly",
        atob: "readonly",
        btoa: "readonly",
        confirm: "readonly",
        alert: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        // Project globals
        App: "writable",
        EcoAI: "writable",
        EcoDashboard: "writable",
        EcoPledges: "writable",
        EcoDb: "writable",
        EcoUtils: "writable",
        Utils: "writable",
        DOMPurify: "readonly",
        confetti: "readonly",
        L: "readonly",
        Chart: "readonly",
        html2canvas: "readonly",
        firebase: "readonly",
        google: "readonly",
        GOOGLE_CLIENT_ID: "readonly",
        ECOTWIN_CONFIG: "readonly",
        lucide: "readonly",
        ProfilePage: "writable",
        EcoCalculator: "writable",
        EcoTwin: "writable",
        EcoScanners: "writable",
        EcoHeroEarth: "writable",
        EcoPlanet: "writable",
        EcoDiagnostics: "writable",
        // Node globals (tests)
        module: "readonly",
        require: "readonly",
        global: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
      "no-undef": "error",
      "no-console": "off",
      "semi": ["warn", "always"],
      "eqeqeq": ["warn", "always"],
      "no-var": "warn",
      "prefer-const": "warn",
    },
  },
  {
    // Test files get relaxed rules
    files: ["tests/**/*.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        jest: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
    },
  },
  {
    ignores: ["node_modules/**", "coverage/**", "css/bundle.css", "scratch/**"],
  },
];
